[project]
name = "line-game"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "pudu-ui",
]

[tool.uv.sources]
pudu-ui = { path = "../pudu-ui", editable = true }
